# Generated by YCM Generator at 2016-05-08 00:05:32.299091

# This file is NOT licensed under the GPLv3, which is the license for the rest
# of YouCompleteMe.
#
# Here's the license text for this file:
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>

import os
import ycm_core

flags = [
    '-x',
    'c',
    '-DAL_ALEXT_PROTOTYPES',
    '-DAL_BUILD_LIBRARY',
    '-DAL_LIBTYPE_STATIC',
    '-DFT2_BUILD_LIBRARY',
    '-DGLEW_NO_GLU',
    '-DGLEW_STATIC',
    '-DSDL2_EXPORTS',
    '-DUSING_GENERATED_CONFIG_H',
    '-D_DEBUG',
    '-D_GNU_SOURCE=1',
    '-D_POSIX_C_SOURCE=200809L',
    '-D_THREAD_SAFE',
    '-D_XOPEN_SOURCE=700',
    '-Dopenal_EXPORTS',
    '-I/Users/muresanvlad/Dev/CLove/src/3rdparty/SDL2/include',
    '-I/Users/muresanvlad/Dev/CLove/src/3rdparty/freetype/include',
    '-I/Users/muresanvlad/Dev/CLove/src/3rdparty/freetype/src/autofit',
    '-I/Users/muresanvlad/Dev/CLove/src/3rdparty/freetype/src/psaux',
    '-I/Users/muresanvlad/Dev/CLove/src/3rdparty/freetype/src/psnames',
    '-I/Users/muresanvlad/Dev/CLove/src/3rdparty/freetype/src/raster',
    '-I/Users/muresanvlad/Dev/CLove/src/3rdparty/freetype/src/sfnt',
    '-I/Users/muresanvlad/Dev/CLove/src/3rdparty/freetype/src/smooth',
    '-I/Users/muresanvlad/Dev/CLove/src/3rdparty/freetype/src/truetype',
    '-I/Users/muresanvlad/Dev/CLove/src/3rdparty/glew/include',
    '-I/Users/muresanvlad/Dev/CLove/src/3rdparty/lua',
    '-I/Users/muresanvlad/Dev/CLove/src/3rdparty/openal/Alc',
    '-I/Users/muresanvlad/Dev/CLove/src/3rdparty/openal/OpenAL32/Include',
    '-I/Users/muresanvlad/Dev/CLove/src/3rdparty/openal/include',
    '-I/Users/muresanvlad/Dev/CLove/src/3rdparty/stb',
    '-I/private/var/folders/28/f0lgfrdd5bv8k6jq48jslvwm0000gp/T/tmpAuwlx5/src/3rdparty/SDL2/include',
    '-I/private/var/folders/28/f0lgfrdd5bv8k6jq48jslvwm0000gp/T/tmpAuwlx5/src/3rdparty/freetype/include/freetype2',
    '-I/private/var/folders/28/f0lgfrdd5bv8k6jq48jslvwm0000gp/T/tmpAuwlx5/src/3rdparty/openal',
    '-Wall',
    '-Wextra',
    '-Winline',
    '-install_name',
    '-std=c99',
    '-std=gnu99',
]


# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# You can get CMake to generate this file for you by adding:
#   set( CMAKE_EXPORT_COMPILE_COMMANDS 1 )
# to your CMakeLists.txt file.
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags. Notice that YCM itself uses that approach.
compilation_database_folder = ''

if os.path.exists( compilation_database_folder ):
  database = ycm_core.CompilationDatabase( compilation_database_folder )
else:
  database = None

SOURCE_EXTENSIONS = [ '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]

def DirectoryOfThisScript():
  return os.path.dirname( os.path.abspath( __file__ ) )


def MakeRelativePathsInFlagsAbsolute( flags, working_directory ):
  if not working_directory:
    return list( flags )
  new_flags = []
  make_next_absolute = False
  path_flags = [ '-isystem', '-I', '-iquote', '--sysroot=' ]
  for flag in flags:
    new_flag = flag

    if make_next_absolute:
      make_next_absolute = False
      if not flag.startswith( '/' ):
        new_flag = os.path.join( working_directory, flag )

    for path_flag in path_flags:
      if flag == path_flag:
        make_next_absolute = True
        break

      if flag.startswith( path_flag ):
        path = flag[ len( path_flag ): ]
        new_flag = path_flag + os.path.join( working_directory, path )
        break

    if new_flag:
      new_flags.append( new_flag )
  return new_flags


def IsHeaderFile( filename ):
  extension = os.path.splitext( filename )[ 1 ]
  return extension in [ '.h', '.hxx', '.hpp', '.hh' ]


def GetCompilationInfoForFile( filename ):
  # The compilation_commands.json file generated by CMake does not have entries
  # for header files. So we do our best by asking the db for flags for a
  # corresponding source file, if any. If one exists, the flags for that file
  # should be good enough.
  if IsHeaderFile( filename ):
    basename = os.path.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if os.path.exists( replacement_file ):
        compilation_info = database.GetCompilationInfoForFile(
          replacement_file )
        if compilation_info.compiler_flags_:
          return compilation_info
    return None
  return database.GetCompilationInfoForFile( filename )


def FlagsForFile( filename, **kwargs ):
  if database:
    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object
    compilation_info = GetCompilationInfoForFile( filename )
    if not compilation_info:
      return None

    final_flags = MakeRelativePathsInFlagsAbsolute(
      compilation_info.compiler_flags_,
      compilation_info.compiler_working_dir_ )

  else:
    relative_to = DirectoryOfThisScript()
    final_flags = MakeRelativePathsInFlagsAbsolute( flags, relative_to )

  return {
    'flags': final_flags,
    'do_cache': True
  }

